## Assisted-by: Claude Opus 5 and Claude Fable 5.1 (Anthropic). See the
## Provenance section of README.md.
##
## Builds every expression matrix the other data-raw scripts consume. They
## used to take pre-made .rds files whose construction lived only in shell
## history, which meant the published figures could not be regenerated by
## anyone, including us once the session ended.
##
##   THCA_GDC=<dir> GSE33630_CEL=<dir> BUILD_OUT=<dir> \
##       Rscript data-raw/build_inputs.R
##
## affy::rma() may die with "return code from pthread_create() is 22" while
## background correcting. It is preprocessCore, not the BLAS -- limiting
## OMP_NUM_THREADS does not help. Rebuild it without threading:
##
##   BiocManager::install("preprocessCore", type = "source", force = TRUE,
##                        configure.args = "--disable-threading")
##
## The result is unchanged; only the threading is.
##
## THCA_GDC       a GDCdownload() directory of TCGA-THCA "STAR - Counts"
## THCA_PREPARED  instead of the above, an .rds holding a GDCprepare(
##                summarizedExperiment = FALSE) data frame. Lets the build be
##                repeated offline and against a fixed snapshot, which is
##                what the verification against the previous matrices used.
## GSE33630_CEL   a directory of GSE33630 .CEL(.gz) files (optional)
## BUILD_OUT      where to write (default: the working directory)
##
## Writes thca_counts.rds, thca_log2tpm.rds, derive_input.rds and, when the
## CEL files are given, gse33630.rds.
##
## ---------------------------------------------------------------------------
## Decisions this script exists to pin down
##
## Each of these was made implicitly before and is now explicit, because an
## implicit choice is one nobody can check.
##
## 1. Gene model. GENCODE v36, the one GDC's STAR counts ship with. Recorded
##    in the output so a later rebuild against another release is visible
##    rather than silent.
##
## 2. One aliquot per patient. Primary tumors only (barcode positions 14-15
##    equal to "01"). Five patients have both an -01A and an -01B aliquot;
##    the vial letter is sorted and the first is taken, so the choice does
##    not depend on file order. Before, it fell out of whatever order the
##    columns happened to be in.
##
## 3. Collapsing duplicated gene symbols. Counts are SUMMED across rows
##    sharing a symbol, and TPM is summed likewise. This is the change that
##    matters most: the two matrices used to disagree. Counts were summed
##    while TPM kept the single highest-expressed row, so the validation and
##    the re-derivation ran on different gene matrices and nothing said so.
##    Summing is right for counts, and TPM is a linear function of counts
##    within a sample, so summing is right there too.
##
## 4. Expression filter. edgeR::filterByExpr() with the driver groups as
##    `group`, on the BRAF/RAS reference samples only, since that is the
##    comparison the signature is derived from.
##
## 5. "Coding". gene_type == "protein_coding", plus ANXA2P2 kept by hand:
##    it is a pseudogene and a published signature member, and dropping it
##    would handicap the signature in a comparison meant to test the
##    signature.
##
## 6. GSE33630. Built from the CEL files with RMA and collapsed to symbols by
##    the highest-variance probe set, variance taken over all 105 arrays
##    (tumors, anaplastic carcinomas and normals alike) before the diagnosis
##    split, so one probe set represents a gene in every group. The matrix
##    used before came from
##    elsewhere and had lost ITGA3 and RASGEF1B to a filter nobody here
##    controlled; building from the CELs restores them, so the microarray
##    figures move slightly. That is the correct direction.
##
##    The series holds 105 arrays, not the 94 the earlier matrix had: 49
##    papillary carcinomas, 11 anaplastic ones and 45 matched normals. The
##    anaplastic samples are a different disease and scoring them as papillary
##    would be wrong, so the diagnosis is read from the GEO sample annotation
##    rather than guessed from file names, and the three groups are labelled
##    in the output.

suppressPackageStartupMessages({
    library(edgeR)
})

source(file.path("data-raw", "record_session.R"))

gdc_dir <- Sys.getenv("THCA_GDC", "")
cel_dir <- Sys.getenv("GSE33630_CEL", "")
out_dir <- Sys.getenv("BUILD_OUT", ".")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

GENE_MODEL <- "GENCODE v36"


## ---- TCGA ---------------------------------------------------------------

## GDC ships one tsv per aliquot, named by file UUID, with the barcode only
## in the query metadata. TCGAbiolinks::GDCprepare() is what puts the two
## together.
read_gdc <- function(dir) {
    prepared <- Sys.getenv("THCA_PREPARED", "")
    if (nzchar(prepared)) {
        message("reading a prepared GDC snapshot from ", prepared)
        return(readRDS(prepared))
    }
    if (!nzchar(dir) || !dir.exists(dir)) {
        stop("Set THCA_GDC to a GDCdownload() directory, or THCA_PREPARED ",
             "to a prepared snapshot; see the header.")
    }
    message("preparing TCGA-THCA from ", dir)
    query <- TCGAbiolinks::GDCquery(
        project = "TCGA-THCA",
        data.category = "Transcriptome Profiling",
        data.type = "Gene Expression Quantification",
        workflow.type = "STAR - Counts"
    )
    TCGAbiolinks::GDCprepare(query, directory = normalizePath(dir),
                             summarizedExperiment = FALSE)
}

## Sum the rows that share a gene symbol. Applied to counts and to TPM alike
## so the two matrices describe the same genes -- see decision 3.
collapse_symbols <- function(mat, symbols) {
    ok <- !is.na(symbols) & nzchar(symbols)
    rowsum(mat[ok, , drop = FALSE], group = symbols[ok], reorder = TRUE)
}

## One primary-tumor aliquot per patient, chosen by sorted vial so the result
## does not depend on column order -- see decision 2.
one_aliquot_per_patient <- function(mat) {
    keep <- substr(colnames(mat), 14, 15) == "01"
    mat <- mat[, keep, drop = FALSE]

    patient <- substr(colnames(mat), 1, 12)
    mat <- mat[, order(patient, colnames(mat)), drop = FALSE]
    patient <- substr(colnames(mat), 1, 12)

    mat <- mat[, !duplicated(patient), drop = FALSE]
    colnames(mat) <- patient[!duplicated(patient)]
    mat
}

raw <- read_gdc(gdc_dir)

is_gene <- !grepl("^N_", as.character(raw$gene_id))
ann <- data.frame(
    gene_id = as.character(raw$gene_id)[is_gene],
    gene_name = as.character(raw$gene_name)[is_gene],
    gene_type = as.character(raw$gene_type)[is_gene],
    stringsAsFactors = FALSE
)

grab <- function(prefix) {
    cols <- grep(paste0("^", prefix), colnames(raw), value = TRUE)
    mat <- as.matrix(raw[is_gene, cols])
    colnames(mat) <- sub(paste0("^", prefix), "", cols)
    mat
}

counts <- grab("unstranded_")
tpm <- grab("tpm_unstranded_")
stopifnot(identical(dim(counts), dim(tpm)))

message("  ", nrow(counts), " genes x ", ncol(counts), " aliquots")

counts_sym <- collapse_symbols(counts, ann$gene_name)
tpm_sym <- collapse_symbols(tpm, ann$gene_name)
stopifnot(identical(rownames(counts_sym), rownames(tpm_sym)))
message("  ", nrow(counts_sym), " unique gene symbols after summing duplicates")

counts_pt <- one_aliquot_per_patient(counts_sym)
tpm_pt <- one_aliquot_per_patient(tpm_sym)
stopifnot(identical(colnames(counts_pt), colnames(tpm_pt)))
message("  ", ncol(counts_pt), " primary tumors, one aliquot each")

log2tpm <- log2(tpm_pt + 1)
saveRDS(log2tpm, file.path(out_dir, "thca_log2tpm.rds"))
saveRDS(list(counts = counts_pt, ann = ann, gene_model = GENE_MODEL),
        file.path(out_dir, "thca_counts.rds"))


## ---- the derivation input ----------------------------------------------

ref <- read.csv(
    file.path("inst", "extdata", "thca_reference.csv"),
    stringsAsFactors = FALSE
)
groups <- setNames(ref$driver_group, ref$patient)
groups <- groups[groups %in% c("BRAF_V600E", "RAS") &
                     names(groups) %in% colnames(counts_pt)]
message("  reference groups: ", sum(groups == "BRAF_V600E"), " BRAF-V600E, ",
        sum(groups == "RAS"), " RAS")

dge <- DGEList(counts_pt[, names(groups)], group = factor(groups))
keep <- rownames(dge)[filterByExpr(dge)]
coding <- unique(c(ann$gene_name[ann$gene_type == "protein_coding"],
                   "ANXA2P2"))
message("  universe: ", length(keep), " expressed genes, ",
        length(intersect(keep, coding)), " of them coding")

saveRDS(
    list(counts = counts_pt, keep = keep, coding = coding, grp = groups,
         gene_model = GENE_MODEL),
    file.path(out_dir, "derive_input.rds")
)


## ---- GSE33630 -----------------------------------------------------------

if (nzchar(cel_dir) && dir.exists(cel_dir)) {
    suppressPackageStartupMessages({
        library(affy)
        library(hgu133plus2.db)
        library(GEOquery)
    })
    message("building GSE33630 from ", cel_dir)

    cels <- list.files(cel_dir, pattern = "[.]CEL([.]gz)?$",
                       ignore.case = TRUE, full.names = TRUE)
    eset <- affy::rma(affy::ReadAffy(filenames = cels))
    expr <- Biobase::exprs(eset)
    colnames(expr) <- sub("_.*$", "", basename(colnames(expr)))

    ## Probe sets to symbols, keeping the most variable probe set per gene:
    ## averaging would blunt exactly the between-sample variation the score
    ## reads.
    map <- AnnotationDbi::select(
        hgu133plus2.db, keys = rownames(expr),
        keytype = "PROBEID", columns = "SYMBOL"
    )
    map <- map[!is.na(map$SYMBOL) & map$PROBEID %in% rownames(expr), ]
    variance <- apply(expr[map$PROBEID, , drop = FALSE], 1, stats::var)
    map <- map[order(map$SYMBOL, -variance), ]
    map <- map[!duplicated(map$SYMBOL), ]

    arr <- expr[map$PROBEID, , drop = FALSE]
    rownames(arr) <- map$SYMBOL
    message("  ", nrow(arr), " symbols x ", ncol(arr), " arrays")

    ## Which array is which disease comes from the series annotation, the
    ## only place that records it.
    series <- GEOquery::getGEO("GSE33630", GSEMatrix = TRUE, getGPL = FALSE)
    pheno <- Biobase::pData(Biobase::phenoData(series[[1]]))
    diagnosis <- as.character(pheno[["characteristics_ch1"]])
    group <- ifelse(grepl("papillary", diagnosis, ignore.case = TRUE), "PTC",
             ifelse(grepl("anaplastic", diagnosis, ignore.case = TRUE), "ATC",
                    "normal"))
    names(group) <- rownames(pheno)

    stopifnot(
        "every array should appear in the series annotation" =
            all(colnames(arr) %in% names(group)),
        ## Without this the whole series can fall through the ifelse chain to
        ## "normal" -- if GEO moves the diagnosis to characteristics_ch1.1,
        ## say -- leaving an empty PTC matrix that saves without complaint.
        "the series should hold 49 PTC, 11 ATC and 45 normals" =
            identical(as.integer(table(factor(group,
                                              levels = c("ATC", "normal",
                                                         "PTC")))),
                      c(11L, 45L, 49L))
    )
    group <- group[colnames(arr)]
    message("  ", paste(names(table(group)), table(group), sep = "=",
                        collapse = "  "))

    saveRDS(
        list(all = arr, group = group, ptc = arr[, group == "PTC"],
             probe_map = map),
        file.path(out_dir, "gse33630.rds")
    )
} else {
    message("GSE33630_CEL not set; skipping the microarray matrix")
}

record_session("build_inputs")
